apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: mysql
      version: 13.0.0
    sourceRef:
      kind: HelmRepository
      name: mysql
      namespace: default
    interval: 10s
