apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
matadata:
  name: infra-controllers
  namespsace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  sourceRef: 
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/contollers
  prune: true
  wait: true
  timeout: 5m0s
